CREATE GLOBAL TEMPORARY TABLE "SYSDBA"."##HISTOGRAMS_TABLE"
(
"OWNER" VARCHAR(128),
"TABLE_NAME" VARCHAR(128),
"COLUMN_NAME" VARCHAR(128),
"HISTOGRAM" VARCHAR(15),
"ENDPOINT_VALUE" VARCHAR(128),
"ENDPOINT_HEIGHT" BIGINT,
"ENDPOINT_KEYHEIGHT" BIGINT,
"ENDPOINT_DISTINCT" BIGINT)
ON COMMIT DELETE ROWS STORAGE(ON TEMP);

CREATE GLOBAL TEMPORARY TABLE "SYSDBA"."##PLAN_TABLE"
(
"PLAN_ID" INT,
"PLAN_NAME" VARCHAR(128),
"CREATE_TIME" DATETIME(6),
"LEVEL_ID" INT,
"OPERATION" VARCHAR(30),
"TAB_NAME" VARCHAR(128),
"IDX_NAME" VARCHAR(128),
"SCAN_TYPE" VARCHAR(20),
"SCAN_RANGE" VARCHAR(128),
"ROW_NUMS" BIGINT,
"BYTES" INT,
"COST" BIGINT,
"CPU_COST" BIGINT,
"IO_COST" BIGINT,
"FILTER" VARCHAR(1000),
"JOIN_COND" VARCHAR(1000),
"ADVICE_INFO" VARCHAR(1000),
"PSTART" INT,
"PSTOP" INT)
ON COMMIT PRESERVE ROWS STORAGE(ON TEMP);

CREATE TABLE "SYSDBA"."category"
(
"id" BIGINT IDENTITY(1, 1) NOT NULL,
"name" VARCHAR(255),
"NUMBER" VARCHAR(255),
NOT CLUSTER PRIMARY KEY("id")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "SYSDBA"."cloth"
(
"id" BIGINT IDENTITY(1, 1) NOT NULL,
"classification" VARCHAR(255),
"gender" VARCHAR(255),
"name" VARCHAR(255),
"NUMBER" VARCHAR(255),
"picture" VARCHAR(255),
"price" DOUBLE NOT NULL,
NOT CLUSTER PRIMARY KEY("id")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "SYSDBA"."dress"
(
"id" BIGINT IDENTITY(1, 1) NOT NULL,
"clothnumber" VARCHAR(255),
"username" VARCHAR(255),
"zindex" INTEGER NOT NULL,
NOT CLUSTER PRIMARY KEY("id")) STORAGE(ON "MAIN", CLUSTERBTR) ;

CREATE TABLE "SYSDBA"."users"
(
"id" BIGINT IDENTITY(1, 1) NOT NULL,
"gender" INTEGER,
"isadmin" INTEGER,
"model" VARCHAR(255),
"PASSWORD" VARCHAR(255),
"relname" VARCHAR(255),
"username" VARCHAR(255),
NOT CLUSTER PRIMARY KEY("id")) STORAGE(ON "MAIN", CLUSTERBTR) ;

